#!/bin/sh
set -e

./bootstrap

wd=`pwd`
revision=`git rev-list --count HEAD`
version=affine-0.3.$revision
cd /tmp
ln -nsf "$wd" "$version"
tar c --exclude=.git -h -z -f "$version.tar.gz" "$version"
rm -f "$version"
